### ISSUE TITLE
 [Everforest] ColorScheme not working correctly

### ISSUE THREAD

**Issue by krstfz** [vinceliuice/Colloid-gtk-theme#159] opened 2024-05-02 10:00 UTC
Hello,

I've noticed that the Everforest color scheme doesn't show properly, neither in GTK3 apps (eg. Nemo) or specific GTK2 apps (eg. Nitrogen). No issues with other color schemes (Dracula, Nord and Gruvbox work flawlessly). Any help?
Thanks for your hard work!

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/0ca555fb-dd58-46d3-81dc-b505a15d5d18)
![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/498ccd86-4b07-4c1f-a51f-ab24d6a53d07)

**Comment by nclslbrn** [comment] 2024-05-02 16:51
Hello, 

Thanks for reporting this, I'll try to reproduce this bug. How do you get these errors, is it during compilation and installation (./Colloid-gtk-theme/install.sh ...) or is it by inspecting the theme with a particular tool ?

**Comment by krstfz** [comment] 2024-05-02 17:07
Hi,

nope, the compiling works fine. I've installed all the color schemes and the process went well without any errors whatsoever. I'm using "lxappearance" to set the themes in i3wm and it works with the other color schemes, no issues there.

The error message in Terminal occurs when I try to launch a gtk2 application through it (like Nitrogen). It doesn't happen with the other theme variants like Dracula etc. 

Thanks again for your help, appreciate the quick response

**Comment by nclslbrn** [comment] 2024-05-02 17:27
Yes, looks like something is missing here.
![Capture d’écran du 2024-05-02 19-27-57](https://github.com/vinceliuice/Colloid-gtk-theme/assets/1374627/b266fd5a-1947-414b-bf04-657e964628d3)
.

**Comment by nclslbrn** [comment] 2024-05-02 17:47
It should be fixed with these changes https://github.com/vinceliuice/Colloid-gtk-theme/pull/160

**Comment by krstfz** [comment] 2024-05-02 17:52
Awesome, thank you once again for your help and hard work. I really appreciate it.

**Comment by vinceliuice** [comment] 2024-05-02 22:37
Fixed now

**Closed** 2024-05-11 14:57 UTC
