### ISSUE TITLE
Bug - Transparent dialog boxes

### ISSUE THREAD

**Issue by peppidesu** [vinceliuice/Colloid-gtk-theme#134] opened 2023-12-01 14:01 UTC
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/29015232/b861bd10-d388-4a28-bb50-bf010584fe3e)

This has been occurring on my fork of the theme, but I can confirm this also happens on the unmodified theme.

Basically, some popup windows will appear without a background color, making them very difficult to read. This is in Hyprland, but I have seen the same happen in GNOME as well.

If i remember correctly, this started becoming an issue after updating to GNOME 45.

EDIT: Adwaita does not have this issue, this is an issue with the theme. I did notice that with Adwaita the dialog slowly fades in, which could indicate this having something to do with a transition property rather than a background property.

**Comment by nicholas-roether** [comment] 2024-04-01 07:00
I don't mean to spam or seem impatient, but this issue has been open, _along with a PR that fixes it_, for 4 months now. @vinceliuice, any update on when this can be addressed?

**Comment by peppidesu** [comment] 2024-04-02 15:50
@nicholas-roether I feel your frustration as well, but lets not pressure vince about undermaintaining this project, we've seen just this weekend what that culture has led us to.

If you are bothered by this you can fork this project and pull from my PR branch to create a personal "more fixed" version for the time being. Let me know if you need help with this

**Comment by nicholas-roether** [comment] 2024-04-03 10:02
@peppidesu You're right. My comment wasn't intended to come off as impatient or demanding, I was just trying to make sure this issue wasn't forgotten about. I think I might make a fork like you said at some point if I find the time :)

**Comment by vinceliuice** [comment] 2024-04-28 23:46
Does this issue still exist?

**Comment by niko-roether** [comment] 2024-11-26 09:49
Sorry, I forgot this issue was still open! I can't speak for @peppidesu, but I can't reproduce the issue anymore, so it seems to have been fixed by #135. Thanks for merging it :)

**Closed** 2024-11-26 10:19 UTC
